### ISSUE TITLE
[Request] Package as library module and present on Android Arsenal

### ISSUE THREAD

**Issue by h6ah4i** [danoz73/RecyclerViewFastScroller#11]
First, I think this library is superb, because many Android developers desire fast scrolling feature for RecyclerView. However, it's not handy to use this library from other app project, and still a bit buggy for now...

I suggest that package this library as a library module and present on the Android Arsenal site as soon as possible. If this library becomes more famous, hopefully developers will contribute :smile:

**Comment by h6ah4i** [comment]
Fixed in my forked branch.

https://github.com/h6ah4i/RecyclerViewFastScroller/tree/separate_library_module

(not PR yet, because other pending PRs conflicts to this modification)

**Comment by h6ah4i** [comment]
Yeah. This library has been listed on the Android Arsenal site.

**Comment by h6ah4i** [comment]
Should put a badge on README.

[![Android Arsenal](https://img.shields.io/badge/Android%20Arsenal-RecyclerViewFastScroller-brightgreen.svg?style=flat)](http://android-arsenal.com/details/1/1582)

**Comment by danoz73** [comment]
Has been turned into a library project. No plans to manage support on android arsenal right now. I'm not familiar with the community.
