### ISSUE TITLE
import error: Error:No such property: OSSRH_USERNAME for class: ...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [danoz73/RecyclerViewFastScroller#19]
I keep getting this error when trying to import the project into Android-Studio:

Error:No such property: OSSRH_USERNAME for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

What is this? How can I fix this?

**Comment by KennyGoers** [comment]
Go to the graddle.settings file and add the defs or comment out the publish bits from the build file. poke around and you should find it.

**Comment by AndroidDeveloperLB** [comment]
which file exactly, and what exactly to put there ? Only similar file is "settings.gradle" , and its content is just that:

include ':recyclerviewfastscroller'
include 'Application'

**Comment by AndroidDeveloperLB** [comment]
I think this is the cause to the issue:
![untitled20150321212643](https://cloud.githubusercontent.com/assets/5357526/6766493/0619a366-d011-11e4-9df4-b9de860720b5.png)

**Comment by IlyaEremin** [comment]
You need only recyclerviewfastscroller folder to import library into your project.
After that put these constant:

```
ext {
    compileSdkVersion = 21
    buildToolsVersion = '21.1.1'
    targetSdkVersion = 21
    minSdkVersion = 14
    versionCode = 0
    versionName = "0.1.0"
}
```
to your build.gradle root file
and

Remove 
```
apply from: 'gradle-maven-push.gradle'

afterEvaluate {
    androidJavadocs.classpath += project.android.libraryVariants.toList().first().javaCompile.classpath
}
```
from build.gradle in recyclerviewfastscroller folder

**Comment by IlyaEremin** [comment]
@danoz73 I successfully imported library as project to android studio. This is no problem with the project. Issue can be closed.

**Comment by AndroidDeveloperLB** [comment]
@IlyaEremin I don't understand. How did you import the project without any needed step? Why do I keep getting this error? 
I just try to import it like any other Github project :
VCS-> Checkout from version control -> Git -> "https://github.com/danoz73/RecyclerViewFastScroller.git" ->Clone .

**Comment by IlyaEremin** [comment]
@AndroidDeveloperLB I updated previous comment, please read it :)

**Comment by IlyaEremin** [comment]
@AndroidDeveloperLB sorry, I think that you want to just import library itself without sample. You can compile sample just by deleting 
```
apply from: 'gradle-maven-push.gradle'
afterEvaluate {
    androidJavadocs.classpath += project.android.libraryVariants.toList().first().javaCompile.classpath
}
```
from `recyclerviewfastscroller/build.gradle`

**Comment by AndroidDeveloperLB** [comment]
@IlyaEremin I don't understand what you mean. Do you suggest creating a new project, downloading only the library part, and import it as a module?
If so, this is a lot more steps than the way I know of, and it also won't import the sample to test it.

**Comment by AndroidDeveloperLB** [comment]
ok, I've deleted both and now it works. What do those lines do anyway?

**Comment by IlyaEremin** [comment]
@AndroidDeveloperLB something related with uploading on maven. I don't know exactly what but it doesn't affect on library using.

**Comment by AndroidDeveloperLB** [comment]
Thank you for helping. I think you should check it out, as I never had this issue on other repositories (thought I do have other issues from time to time).

**Comment by danoz73** [comment]
Thanks for identifying this issue. 

Those lines were, by default, including the configuration of the maven upload task that I have for my own convenience. I have now made it a requirement to specifically specify a gradle property `recyclerviewfastscroller.uploadScript` in order to actually use the `uploadArchives` task.

**Comment by AndroidDeveloperLB** [comment]
I don't understand, but thank you for fixing this.
