### ISSUE TITLE
Request: add support to SectionIndexer and show the bubble-popup like on Lollipop's contacts app

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [danoz73/RecyclerViewFastScroller#2]
as the title says.

**Comment by danoz73** [comment]
b3e2d2fa8284dea31fbc5f9f218199f2a187a657 adds this functionality. Check out the `RecyclerViewWithSectionIndicatorFragment` and the `SectionIndicator` classes for implementation details.

**Comment by AndroidDeveloperLB** [comment]
Cool ! does the sample have it too?

**Comment by danoz73** [comment]
Yeah run the APK and open the options menu to go to the section fragment

**Comment by AndroidDeveloperLB** [comment]
I've noticed that the popup doesn't show on the correct Y coordinate, in relation to the fast-scroller .
Also, when scrolling to the top, it looks as if it snaps to the top, while it's smooth for the bottom.
Please fix those issues too.
