### ISSUE TITLE
Cannot load dependency

### ISSUE THREAD

**Issue by sirvar** [danoz73/RecyclerViewFastScroller#38]
Getting an error when adding compile 'xyz.danoz:recyclerviewfastscroller:0.1.3' into dependency section of build.gradle. 

> Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
> Could not find com.android.support:recyclerview-v7:22.1.0.
>      Required by:
>          XXX:app:unspecified
>          XXX:app:unspecified > xyz.danoz:recyclerviewfastscroller:0.1.3
> Could not find com.android.support:support-v4:22.1.0.
>      Required by:
>          XXX:app:unspecified > xyz.danoz:recyclerviewfastscroller:0.1.3

**Comment by alibitek** [comment]
@rikinkatyal Your problem is not related to RecyclerViewFastScroller, but with Android Support library.
Did you read the error message?
`
Could not find com.android.support:support-v4:22.1.0.
Required by: [...] xyz.danoz:recyclerviewfastscroller:0.1.3
` 
Do you have Android Support Repository and Android Support Library installed in the Android SDK Manager? 
Do you have  `compile 'com.android.support:support-v4:22.2.0'` in the build.gradle file for your app's module?
Did you run Tools -> Android -> Sync Project with Gradle Files after adding the support library to gradle?

**Comment by sirvar** [comment]
Please see the attached image as to what happens when I use the 22.2.0
dependency.

On Thu, Jun 25, 2015 at 4:49 AM, Mnemonic Flow notifications@github.com
wrote:

> @rikinkatyal https://github.com/rikinkatyal Your problem is not related
> to RecyclerViewFastScroller, but with Android Support library.
> 
> Do you have Android Support Repository and Android Support Library
> installed in the Android SDK Manager?
> Do you have compile 'com.android.support:support-v4:22.2.0' in the
> build.gradle file for your app's module?
> Did you run Tools -> Android -> Sync Project with Gradle Files after
> adding the support library to gradle?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/danoz73/RecyclerViewFastScroller/issues/38#issuecomment-115167900
> .

## 

Thanks
Rikin Katyal

**Comment by alibitek** [comment]
@rikinkatyal Sorry, there is no attached image.  Keep in mind that you need to set the version string according to what Android Support library version you have installed. I'm using the latest version. Run Android SDK Manager and check/update.

**Comment by rikinkatyal** [comment]
https://filetea.me/t1scHux1B2pQDinzQ2NpihPFQ
This is the link to the screenshot.

On Thu, Jun 25, 2015 at 3:29 PM, Mnemonic Flow <notifications@github.com>
wrote:

> @rikinkatyal <https://github.com/rikinkatyal> Sorry, there is no attached
> image. Keep in mind that you need to set the version string according to
> what Android Support library version you have installed. I'm using the
> latest version. Run Android SDK Manager and check/update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danoz73/RecyclerViewFastScroller/issues/38#issuecomment-115370428>
> .
>



-- 
Thanks
Rikin Katyal
