### ISSUE TITLE
Hide ScrollBar when Items are smaller then screen size.

### ISSUE THREAD

**Issue by naushad-madakiya** [danoz73/RecyclerViewFastScroller#69]
`ScrollBar` should not visible when there are low items to show on screen.

![rsz_1device-2017-01-16-213621](https://cloud.githubusercontent.com/assets/8583183/21990534/2d09558e-dc35-11e6-9451-ca600c265c58.png)

**Comment by naushad-madakiya** [comment]
@danoz73 any views on this?

**Comment by NickM-27** [comment]
This could be done manually by the developer as well
